# Copyright (c) 2026, Carl and contributors
# For license information, please see license.txt

import frappe

from test.testing.doctype.testing_entrustment.testing_entrustment import (
	STATUS_QUOTATION_ACCEPTED,
	STATUS_TO_BE_QUOTED,
)


def _get_entrustment_name(quotation):
	return quotation.get("testing_entrustment")


def _link_back(quotation, entrustment_name):
	"""Make sure the entrustment points to this quotation."""
	entrustment = frappe.get_doc("Testing Entrustment", entrustment_name)
	if entrustment.docstatus != 1 or entrustment.quotation == quotation.name:
		return
	if not entrustment.quotation or not frappe.db.exists(
		"Quotation", entrustment.quotation
	):
		frappe.db.set_value(
			"Testing Entrustment", entrustment_name, "quotation", quotation.name
		)


def sync_entrustment_link(quotation, method=None):
	"""Quotation is saved (manually linked or generated by this app)."""
	entrustment_name = _get_entrustment_name(quotation)
	if not entrustment_name or not frappe.db.exists("Testing Entrustment", entrustment_name):
		return
	_link_back(quotation, entrustment_name)


def mark_entrustment_accepted(quotation, method=None):
	entrustment_name = _get_entrustment_name(quotation)
	if not entrustment_name or not frappe.db.exists("Testing Entrustment", entrustment_name):
		return
	entrustment = frappe.get_doc("Testing Entrustment", entrustment_name)
	if entrustment.docstatus != 1:
		return
	_link_back(quotation, entrustment_name)
	frappe.db.set_value(
		"Testing Entrustment",
		entrustment_name,
		{"status": STATUS_QUOTATION_ACCEPTED, "quotation": quotation.name},
	)


def unlink_entrustment(quotation, method=None):
	"""Clear the back-reference when the quotation is cancelled or deleted."""
	entrustment_name = _get_entrustment_name(quotation)
	if not entrustment_name or not frappe.db.exists("Testing Entrustment", entrustment_name):
		return

	entrustment = frappe.get_doc("Testing Entrustment", entrustment_name)
	if entrustment.docstatus == 1 and entrustment.quotation == quotation.name:
		frappe.db.set_value(
			"Testing Entrustment",
			entrustment_name,
			{"quotation": None, "status": STATUS_TO_BE_QUOTED},
		)
